Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('1','Microsoft',to_date('14.04.77','DD.MM.RR'),'998787',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('2','Apple',to_date('27.10.89','DD.MM.RR'),'998788',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('3','Amazon',to_date('27.11.15','DD.MM.RR'),'998789',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('4','Azet',to_date('21.07.99','DD.MM.RR'),'998790',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('5','DaVinci',to_date('22.11.81','DD.MM.RR'),'998791',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('6','Kvetinac',to_date('28.05.91','DD.MM.RR'),'998792',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('7','Eset',to_date('20.11.91','DD.MM.RR'),'998793',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('8','Karol III.',to_date('24.06.88','DD.MM.RR'),'998794',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('9','Pizza Federation',to_date('21.10.86','DD.MM.RR'),'998795',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('10','Michaello',to_date('26.11.81','DD.MM.RR'),'998796',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('11','FRI consulting s.r.o',to_date('25.05.09','DD.MM.RR'),'998797',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('12','Kvietocek Ruzovy',to_date('29.01.01','DD.MM.RR'),'998798',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('13','Apokalypsa',to_date('03.09.02','DD.MM.RR'),'998799',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('14','Zhor v pekle s.r.o.',to_date('25.04.02','DD.MM.RR'),'998800',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('15','AssHole Prievidza',to_date('08.10.77','DD.MM.RR'),'998801',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('16','Handlova Experience a.s.',to_date('07.05.09','DD.MM.RR'),'998802',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('17','Zapotocky-Server Ltd.',to_date('16.03.16','DD.MM.RR'),'998803',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('18','Rutrum Ltd',to_date('21.01.03','DD.MM.RR'),'998804',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('19','Nulla Tempor Incorporated',to_date('14.09.79','DD.MM.RR'),'998805',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('20','Libero Morbi LLC',to_date('27.06.81','DD.MM.RR'),'998806',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('21','Amet Corporation',to_date('04.03.79','DD.MM.RR'),'998807',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('22','Ut Erat Associates',to_date('30.01.14','DD.MM.RR'),'998808',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('23','Mauris Ltd',to_date('27.01.99','DD.MM.RR'),'998809',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('24','Ultrices Mauris Corporation',to_date('25.05.95','DD.MM.RR'),'998810',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('25','Sit Amet Diam Industries',to_date('23.12.15','DD.MM.RR'),'998811',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('26','Luctus Ltd',to_date('06.10.82','DD.MM.RR'),'998812',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('27','Odio Phasellus At Company',to_date('18.05.76','DD.MM.RR'),'998813',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('28','Posuere Cubilia Curae; Institute',to_date('03.09.95','DD.MM.RR'),'998814',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('29','Phasellus Dapibus Corp.',to_date('22.06.04','DD.MM.RR'),'998815',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('30','Justo Sit Amet Inc.',to_date('24.11.83','DD.MM.RR'),'998816',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('31','Cursus Consulting',to_date('05.09.96','DD.MM.RR'),'998817',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('32','Aenean Corporation',to_date('26.05.89','DD.MM.RR'),'998818',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('33','Curabitur Massa Inc.',to_date('19.01.81','DD.MM.RR'),'998819',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('34','Purus Limited',to_date('03.04.03','DD.MM.RR'),'998820',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('35','Porttitor Scelerisque Neque Inc.',to_date('16.03.15','DD.MM.RR'),'998821',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('36','Nunc In At Corp.',to_date('25.11.89','DD.MM.RR'),'998822',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('37','Auctor Odio A PC',to_date('04.09.93','DD.MM.RR'),'998823',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('38','Cras Institute',to_date('13.12.03','DD.MM.RR'),'998824',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('39','Porta Elit A Foundation',to_date('26.04.06','DD.MM.RR'),'998825',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('40','Pede Inc.',to_date('05.08.96','DD.MM.RR'),'998826',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('41','Eget PC',to_date('15.12.08','DD.MM.RR'),'998827',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('42','Enim Institute',to_date('21.04.94','DD.MM.RR'),'998828',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('43','Nunc LLP',to_date('22.05.88','DD.MM.RR'),'998829',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('44','Netus Et Malesuada Corporation',to_date('09.02.11','DD.MM.RR'),'998830',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('45','Nunc Commodo Auctor Corporation',to_date('27.07.88','DD.MM.RR'),'998831',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('46','Proin Vel PC',to_date('06.01.09','DD.MM.RR'),'998832',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('47','Sed Institute',to_date('11.02.04','DD.MM.RR'),'998833',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('48','Aliquam Adipiscing Limited',to_date('28.08.78','DD.MM.RR'),'998834',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('49','Orci Luctus Limited',to_date('26.02.16','DD.MM.RR'),'998835',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('50','Bibendum Sed Incorporated',to_date('16.09.99','DD.MM.RR'),'998836',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('51','Sem Mollis PC',to_date('30.03.12','DD.MM.RR'),'998837',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('52','Ut Incorporated',to_date('04.03.82','DD.MM.RR'),'998838',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('53','In Tincidunt LLC',to_date('28.08.12','DD.MM.RR'),'998839',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('54','Mauris Eu Industries',to_date('11.06.93','DD.MM.RR'),'998840',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('55','Vivamus Ltd',to_date('25.10.91','DD.MM.RR'),'998841',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('56','Non LLP',to_date('22.10.91','DD.MM.RR'),'998842',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('57','Semper Company',to_date('12.08.86','DD.MM.RR'),'998843',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('58','Risus Limited',to_date('23.06.99','DD.MM.RR'),'998844',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('59','Placerat Associates',to_date('28.03.10','DD.MM.RR'),'998845',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('60','Purus Sapien Consulting',to_date('28.04.87','DD.MM.RR'),'998846',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('61','Eu Eros Nam Corporation',to_date('30.05.87','DD.MM.RR'),'998847',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('62','Erat PC',to_date('27.01.99','DD.MM.RR'),'998848',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('63','Arcu Limited',to_date('21.07.91','DD.MM.RR'),'998849',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('64','Non Ante Ltd',to_date('01.06.90','DD.MM.RR'),'998850',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('65','Primis In Faucibus Associates',to_date('26.03.07','DD.MM.RR'),'998851',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('66','Natoque Associates',to_date('17.11.92','DD.MM.RR'),'998852',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('67','Aenean Massa Integer Institute',to_date('21.05.03','DD.MM.RR'),'998853',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('68','Eget Lacus Mauris Corporation',to_date('21.12.79','DD.MM.RR'),'998854',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('69','Praesent Corp.',to_date('02.08.97','DD.MM.RR'),'998855',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('70','Amet Faucibus Ut LLP',to_date('27.04.79','DD.MM.RR'),'998856',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('71','A Limited',to_date('06.08.08','DD.MM.RR'),'998857',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('72','Luctus Incorporated',to_date('09.05.15','DD.MM.RR'),'998858',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('73','Eros Proin Ultrices Corporation',to_date('09.05.02','DD.MM.RR'),'998859',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('74','Tempor Erat Neque PC',to_date('02.02.14','DD.MM.RR'),'998860',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('75','Cursus In Associates',to_date('09.12.75','DD.MM.RR'),'998861',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('76','Non Ante LLP',to_date('16.03.96','DD.MM.RR'),'998862',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('77','Massa Lobortis PC',to_date('23.07.11','DD.MM.RR'),'998863',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('78','Aliquam PC',to_date('22.02.89','DD.MM.RR'),'998864',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('79','Sed Inc.',to_date('01.12.83','DD.MM.RR'),'998865',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('80','Vitae Risus LLP',to_date('18.04.92','DD.MM.RR'),'998866',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('81','Mus Corp.',to_date('03.02.88','DD.MM.RR'),'998867',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('82','A Associates',to_date('11.04.15','DD.MM.RR'),'998868',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('83','Aliquet Foundation',to_date('23.03.11','DD.MM.RR'),'998869',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('84','Massa Corporation',to_date('31.12.05','DD.MM.RR'),'998870',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('85','Ut Quam Vel Industries',to_date('09.11.12','DD.MM.RR'),'998871',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('86','Aenean Gravida Company',to_date('16.11.76','DD.MM.RR'),'998872',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('87','Nibh Company',to_date('01.08.05','DD.MM.RR'),'998873',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('88','Lorem Corporation',to_date('02.04.78','DD.MM.RR'),'998874',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('89','Felis Orci Adipiscing PC',to_date('14.05.14','DD.MM.RR'),'998875',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('90','Fusce Aliquam Enim Corp.',to_date('28.10.09','DD.MM.RR'),'998876',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('91','Pede Nunc Sed Ltd',to_date('06.06.95','DD.MM.RR'),'998877',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('92','Quisque Tincidunt Corporation',to_date('12.06.80','DD.MM.RR'),'998878',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('93','Amet Metus Aliquam Corp.',to_date('22.09.07','DD.MM.RR'),'998879',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('94','Enim Non Nisi Inc.',to_date('23.12.82','DD.MM.RR'),'998880',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('95','Quisque Associates',to_date('24.06.16','DD.MM.RR'),'998881',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('96','Donec Inc.',to_date('29.03.05','DD.MM.RR'),'998882',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('97','Lorem Ipsum Dolor LLP',to_date('19.12.76','DD.MM.RR'),'998883',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('98','Nibh Incorporated',to_date('14.09.85','DD.MM.RR'),'998884',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('99','Sed Auctor Odio Associates',to_date('20.01.06','DD.MM.RR'),'998885',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('100','Vestibulum Nec Euismod Foundation',to_date('15.06.00','DD.MM.RR'),'998886',null);
Insert into DRABIKOVA8.D_FIRMA (DIC_FIRMA,NAZOV,DATUM_VZNIKU,ICO,DATUM_ZANIKU) values ('101','Vestibulum Nec Euismod Foundation',to_date('15.06.00','DD.MM.RR'),'998886',null);
