insert into TYP_KONTAKTU(ID_TYP_KONTAKTU,NAZOV_TYPU) VALUES(1,'email');
insert into TYP_KONTAKTU(ID_TYP_KONTAKTU,NAZOV_TYPU) VALUES(2,'mobil');
insert into TYP_KONTAKTU(ID_TYP_KONTAKTU,NAZOV_TYPU) VALUES(3,'telefon');
insert into TYP_KONTAKTU(ID_TYP_KONTAKTU,NAZOV_TYPU) VALUES(4,'ICQ');
insert into TYP_KONTAKTU(ID_TYP_KONTAKTU,NAZOV_TYPU) VALUES(5,'Skype');
insert into TYP_KONTAKTU(ID_TYP_KONTAKTU,NAZOV_TYPU) VALUES(6,'Twitter');
insert into TYP_KONTAKTU(ID_TYP_KONTAKTU,NAZOV_TYPU) VALUES(7,'LinkedIn');
commit;