INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (1,99,'North Battleford');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (2,9,'Ophoven');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (3,24,'Ellikom');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (4,93,'Chatillon');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (5,90,'San Donato di Ninea');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (6,75,'Edinburgh');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (7,92,'Chapadinha');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (8,9,'Heusden');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (9,28,'Wijnegem');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (10,97,'Vitry-sur-Seine');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (11,67,'Cavallino');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (12,13,'Saint-Denis');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (13,92,'Falisolle');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (14,93,'Caramanico Terme');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (15,57,'Grumo Appula');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (16,21,'Habra');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (17,85,'Castellafiume');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (18,37,'Hasselt');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (19,16,'Gistel');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (20,54,'Niel-bij-As');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (21,44,'Bedford');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (22,74,'Eugene');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (23,58,'Serrata');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (24,24,'Jerzu');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (25,26,'Fort Saskatchewan');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (26,52,'Lakeshore');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (27,38,'Middelkerke');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (28,1,'Rio Saliceto');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (29,66,'Clovenfords');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (30,85,'Branchon');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (31,64,'Chaumont-Gistoux');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (32,20,'Rajapalaiyam');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (33,58,'Lochristi');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (34,50,'Aachen');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (35,22,'Zamora');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (36,24,'Cervino');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (37,11,'Huppaye');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (38,98,'Guelph');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (39,53,'Gargazzone/Gargazon');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (40,87,'Builth Wells');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (41,16,'Termini Imerese');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (42,38,'Grand-Rosi?re-Hottomont');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (43,81,'Spijkenisse');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (44,79,'Neustadt am R?benberge');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (45,18,'Llanelli');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (46,51,'Machilipatnam');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (47,58,'Sandy');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (48,25,'Hubli');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (49,5,'Llanwrtwd Wells');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (50,10,'Diegem');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (51,36,'Offenburg');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (52,69,'Macerata');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (53,23,'Gibsons');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (54,11,'Racine');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (55,79,'Armstrong');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (56,10,'Hawick');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (57,26,'Olsztyn');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (58,8,'Banbury');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (59,72,'Accadia');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (60,44,'Allentown');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (61,54,'Emden');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (62,47,'Tilburg');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (63,41,'Ballarat');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (64,22,'Pelotas');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (65,15,'Cranbrook');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (66,44,'Isle-aux-Coudres');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (67,53,'Li?ge');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (68,78,'Sossano');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (69,80,'La Roche-sur-Yon');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (70,73,'Ajaccio');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (71,37,'Tobermory');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (72,16,'Leganés');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (73,50,'Sint-Genesius-Rode');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (74,4,'Worthing');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (75,51,'Bastia Umbra');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (76,17,'Gisborne');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (77,57,'Carcassonne');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (78,27,'Yorkton');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (79,48,'Le Havre');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (80,88,'Graz');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (81,60,'Barahanagar');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (82,54,'Blaenau Ffestiniog');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (83,89,'Hamilton');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (84,72,'Salerno');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (85,70,'Shawville');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (86,36,'St. Johann in Tirol');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (87,4,'Virginia Beach');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (88,90,'Chhindwara');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (89,10,'Bellevue');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (90,23,'Pelago');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (91,52,'Spijkenisse');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (92,38,'San Francisco');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (93,49,'Phoenix');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (94,64,'Tramutola');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (95,1,'Windsor');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (96,65,'Giardinello');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (97,54,'Corbara');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (98,27,'Cargovil');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (99,8,'Hindupur');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (100,27,'Abaetetuba');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (101,54,'Miramichi');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (102,98,'Altidona');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (103,56,'Antwerpen');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (104,7,'Racine');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (105,39,'Cincinnati');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (106,93,'Wandsworth');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (107,16,'Nampa');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (108,75,'Castello Tesino');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (109,7,'Flint');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (110,87,'Vlezenbeek');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (111,75,'Challand-Saint-Victor');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (112,5,'M?nchengladbach');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (113,66,'Cartagena');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (114,46,'Sorbo Serpico');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (115,27,'Ananindeua');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (116,77,'Sambuca Pistoiese');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (117,18,'Nicolosi');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (118,25,'Penticton');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (119,74,'Salt Lake City');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (120,33,'Wattrelos');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (121,45,'Rotheux-Rimi?re');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (122,84,'Schleswig');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (123,25,'Offenburg');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (124,20,'Oudekapelle');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (125,97,'Calice al Cornoviglio');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (126,11,'Chatillon');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (127,47,'Panihati');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (128,78,'Piovene Rocchette');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (129,68,'Roccabruna');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (130,70,'Hilo');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (131,86,'Thon');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (132,31,'Fleurus');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (133,81,'Champdani');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (134,50,'Stonewall');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (135,82,'Almelo');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (136,49,'Tailles');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (137,23,'Griesheim');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (138,25,'Thon');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (139,75,'Medicine Hat');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (140,95,'Terzorio');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (141,39,'Dignano');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (142,23,'Sherborne');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (143,68,'Regina');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (144,52,'Wichita');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (145,68,'Sant''Angelo in Pontano');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (146,23,'Kilwinning');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (147,20,'Calais');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (148,41,'Bossuit');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (149,56,'Fontenoille');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (150,26,'Hof');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (151,11,'Wevelgem');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (152,98,'Erquelinnes');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (153,41,'Wibrin');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (154,34,'Avise');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (155,66,'Campos dos Goytacazes');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (156,76,'Trowbridge');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (157,14,'Jonqui?re');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (158,32,'Allentown');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (159,36,'Ukkel');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (160,70,'Saint-L?onard');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (161,43,'Torgiano');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (162,34,'Prenzlau');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (163,45,'Mobile');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (164,52,'Thirimont');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (165,100,'Osgoode');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (166,82,'Bo''ness');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (167,67,'Damoh');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (168,77,'Springfield');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (169,66,'Juazeiro');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (170,33,'Matlock');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (171,19,'Ellesmere Port');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (172,3,'Anand');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (173,55,'Eckville');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (174,99,'Suxy');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (175,13,'Kolmont');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (176,14,'Sint-Joost-ten-Node');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (177,16,'Fochabers');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (178,37,'Biala Podlaska');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (179,78,'Bingen');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (180,90,'Elingen');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (181,88,'Wattrelos');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (182,65,'Mâcon');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (183,65,'Bientina');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (184,8,'Shahjahanpur');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (185,46,'Beaconsfield');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (186,17,'Avignon');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (187,87,'Ururi');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (188,74,'Frauenkirchen');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (189,29,'Whakatane');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (190,66,'Pitt Meadows');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (191,54,'Kielce');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (192,78,'Oetingen');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (193,14,'Santa Inês');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (194,64,'Schoonaarde');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (195,3,'Tamines');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (196,76,'Cherbourg-Octeville');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (197,70,'Wernigerode');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (198,70,'Terrance');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (199,85,'Wichita');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (200,100,'Novoli');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (201,11,'Agra');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (202,68,'Rupelmonde');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (203,2,'Sutton');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (204,80,'Caen');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (205,37,'Guadalupe');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (206,86,'Tullibody');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (207,44,'Sijsele');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (208,84,'Canora');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (209,68,'Coleville Lake');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (210,82,'Crewe');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (211,2,'North Saanich');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (212,13,'Torgiano');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (213,80,'Tampa');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (214,65,'Kidwelly');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (215,83,'Oklahoma City');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (216,59,'Shawville');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (217,9,'Neerheylissem');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (218,54,'Berhampore');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (219,49,'Rosolini');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (220,61,'Etroubles');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (221,64,'Grosseto');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (222,93,'Leuze');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (223,7,'Waardamme');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (224,6,'Heerhugowaard');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (225,29,'Saint-Pierre');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (226,96,'Ambala Sadar');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (227,57,'Rio Saliceto');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (228,96,'Lutterworth');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (229,78,'Hachy');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (230,4,'Roksem');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (231,25,'Dawson Creek');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (232,26,'Harbour Grace');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (233,16,'March');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (234,42,'Saint-Denis');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (235,77,'Lions Bay');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (236,10,'Veraval');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (237,44,'Vreren');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (238,19,'Gdynia');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (239,24,'Gianico');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (240,59,'Greenlaw');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (241,21,'Hertsberge');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (242,83,'Portici');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (243,3,'Froidchapelle');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (244,11,'Laces/Latsch');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (245,91,'Charleville-Mézières');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (246,49,'Grand-Hallet');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (247,95,'Frederick');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (248,50,'Corroy-le-Grand');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (249,86,'North Saanich');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (250,58,'Braunschweig');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (251,72,'Wambeek');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (252,48,'Kaster');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (253,64,'Nagaon');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (254,80,'Knokke');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (255,14,'Fabro');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (256,92,'Pollein');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (257,14,'Llangefni');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (258,94,'Rum');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (259,58,'Colorado Springs');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (260,62,'Bruderheim');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (261,63,'Grand-Halleux');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (262,78,'Cleveland');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (263,81,'Sant''Elena');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (264,49,'Waidhofen an der Ybbs');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (265,11,'Missoula');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (266,74,'Attigliano');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (267,26,'Salcito');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (268,30,'Yellowknife');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (269,35,'Pointe-du-Lac');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (270,42,'Argyle');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (271,25,'Ludhiana');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (272,87,'Lacombe County');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (273,90,'Itegem');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (274,64,'Rachecourt');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (275,62,'Baileux');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (276,7,'Saint-Marcel');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (277,40,'Zwevegem');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (278,73,'Promo-Control');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (279,14,'Vito d''Asio');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (280,100,'Varna/Vahrn');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (281,91,'Lethbridge');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (282,47,'Jemeppe-sur-Meuse');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (283,99,'Khammam');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (284,45,'Blieskastel');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (285,70,'Saint-Brieuc');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (286,23,'Huntley');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (287,57,'Wadgassen');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (288,16,'Los Angeles');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (289,22,'Thurso');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (290,30,'Stockport');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (291,42,'Overland Park');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (292,31,'Canoas');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (293,85,'Dolceacqua');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (294,7,'Whitburn');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (295,41,'Kansas City');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (296,6,'Elbistan');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (297,28,'Barrow-in-Furness');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (298,95,'Harnoncourt');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (299,62,'Pirna');
INSERT INTO mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (300,38,'Fourbechies');
