INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (1,101,'Banská Bystrica');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (2,101,'Banská Štiavnica');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (3,101,'Bardejov');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (4,101,'Bojnice');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (5,101,'Bratislava');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (6,101,'Brezno');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (7,101,'Brezová pod Bradlom');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (8,101,'Bytca');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (9,101,'Bánovce nad Bebravou');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (10,101,'Detva');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (11,101,'Dobšiná');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (12,101,'Dolný Kubín');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (13,101,'Dubnica nad Váhom');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (14,101,'Dudince');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (15,101,'Dunajská Streda');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (16,101,'Filakovo');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (17,101,'Galanta');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (18,101,'Gbely');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (19,101,'Gelnica');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (20,101,'Giraltovce');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (21,101,'Handlová');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (22,101,'Hanušovce nad Toplou');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (23,101,'Hlohovec');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (24,101,'Hnúšta');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (25,101,'Holíc');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (26,101,'Hrinová');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (27,101,'Humenné');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (28,101,'Hurbanovo');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (29,101,'Ilava');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (30,101,'Jelšava');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (31,101,'Kežmarok');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (32,101,'Kolárovo');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (33,101,'Komárno');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (34,101,'Košice');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (35,101,'Kremnica');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (36,101,'Krompachy');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (37,101,'Krupina');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (38,101,'Krásno nad Kysucou');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (39,101,'Královský Chlmec');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (40,101,'Kysucké Nové d_mesto');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (41,101,'Leopoldov');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (42,101,'Levice');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (43,101,'Levoca');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (44,101,'Lipany');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (45,101,'Liptovský Hrádok');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (46,101,'Liptovský Mikuláš');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (47,101,'Lucenec');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (48,101,'Malacky');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (49,101,'Martin');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (50,101,'Medzev');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (51,101,'Medzilaborce');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (52,101,'Michalovce');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (53,101,'Modra');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (54,101,'Modrý Kamen');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (55,101,'Moldava nad Bodvou');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (56,101,'Myjava');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (57,101,'Nemšová');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (58,101,'Nitra');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (59,101,'Nová Bana');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (60,101,'Nová Dubnica');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (61,101,'Nováky');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (62,101,'Nové d_mesto nad Váhom');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (63,101,'Nové Zámky');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (64,101,'Nád_mestovo');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (65,101,'Partizánske');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (66,101,'Pezinok');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (67,101,'Pieštany');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (68,101,'Podolínec');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (69,101,'Poltár');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (70,101,'Poprad');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (71,101,'Považská Bystrica');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (72,101,'Prešov');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (73,101,'Prievidza');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (74,101,'Púchov');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (75,101,'Rajec');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (76,101,'Rajecké Teplice');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (77,101,'Revúca');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (78,101,'Rimavská Sobota');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (79,101,'Rožnava');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (80,101,'Ružomberok');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (81,101,'Sabinov');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (82,101,'Senec');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (83,101,'Senica');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (84,101,'Sered');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (85,101,'Secovce');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (86,101,'Skalica');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (87,101,'Sliac');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (88,101,'Sládkovicovo');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (89,101,'Snina');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (90,101,'Sobrance');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (91,101,'Spišská Belá');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (92,101,'Spišská Nová Ves');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (93,101,'Spišská Stará Ves');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (94,101,'Spišské Podhradie');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (95,101,'Spišské Vlachy');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (96,101,'Stará Turá');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (97,101,'Stará Lubovna');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (98,101,'Stropkov');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (99,101,'Strážske');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (100,101,'Stupava');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (101,101,'Svidník');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (102,101,'Svit');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (103,101,'Svätý Jur');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (104,101,'Tisovec');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (105,101,'Tlmace');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (106,101,'Topolcany');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (107,101,'Tornala');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (108,101,'Trebišov');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (109,101,'Trencianske Teplice');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (110,101,'Trencín');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (111,101,'Trnava');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (112,101,'Trstená');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (113,101,'Turzovka');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (114,101,'Turcianske Teplice');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (115,101,'Tvrdošín');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (116,101,'Velké Kapušany');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (117,101,'Velký Krtíš');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (118,101,'Velký Meder');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (119,101,'Velký Šariš');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (120,101,'Vranov nad Toplou');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (121,101,'Vrbové');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (122,101,'Vráble');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (123,101,'Vrútky');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (124,101,'Vysoké Tatry');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (125,101,'Zlaté Moravce');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (126,101,'Zvolen');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (127,101,'Cadca');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (128,101,'Cierna nad Tisou');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (129,101,'Šahy');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (130,101,'Šamorín');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (131,101,'Šala');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (132,101,'Šaštín-Stráže');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (133,101,'Štúrovo');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (134,101,'Šurany');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (135,101,'Žarnovica');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (136,101,'Želiezovce');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (137,101,'Žiar nad Hronom');
INSERT INTO d_mesto (id_mesta,id_krajiny,nazov_mesta) VALUES (138,101,'Žilina');