insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (1,112,101,'Bakalárska ulica', '266');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (2,127,101,'Cesta pod Banskou', '30');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (3,85,101,'Cesta pod skalou', '37');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (4,93,101,'Cesta polnohospodárov', '227');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (5,15,101,'Ciglianska cesta', '140');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (6,17,101,'Dlhá ulica', '224');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (7,18,101,'Garážová ulica', '93');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (8,68,101,'Hasicská ulica', '308');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (9,59,101,'Hviezdoslavova ulica', '10');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (10,48,101,'Inžinierska ulica', '267');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (11,21,101,'Kláštorná ulica', '182');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (12,97,101,'Košovská cesta', '39');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (13,52,101,'Kukucínova ulica', '180');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (14,54,101,'Lehotská cesta', '173');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (15,35,101,'Malolehotská ulica', '269');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (16,4,101,'Mariánska ulica', '63');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (17,68,101,'Montážna ulica', '247');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (18,112,101,'Moštenická ulica', '98');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (19,122,101,'Nábrežie A. Kmeta', '228');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (20,120,101,'Nábrežie J. Kalinciaka', '29');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (21,104,101,'Nábrežie sv. Cyrila', '90');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (22,54,101,'Nábrežie sv. Metoda', '110');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (23,50,101,'Nadjazdová ulica', '71');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (24,67,101,'Námestie slobody', '8');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (25,98,101,'Necpalská cesta', '258');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (26,31,101,'Nová ulica', '138');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (27,33,101,'Osadová cesta', '66');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (28,104,101,'Podjazdová ulica', '14');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (29,80,101,'Pribinovo námestie', '70');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (30,69,101,'Priemyselná ulica', '277');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (31,31,101,'Púšt', '283');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (32,61,101,'Rastislavova ulica', '54');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (33,21,101,'Sebedražská cesta', '313');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (34,11,101,'Severná ulica', '262');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (35,127,101,'Sitnianskeho ulica', '127');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (36,28,101,'Skladová ulica', '8');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (37,73,101,'Strojárska ulica', '264');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (38,65,101,'Šumperská ulica', '260');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (39,26,101,'Teplárenská ulica', '1');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (40,59,101,'Ulica A. Hlinku', '95');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (41,106,101,'Ulica A. Škarvana', '293');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (42,9,101,'Ulica G. Švéniho', '297');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (43,135,101,'Ulica J. Hollého', '93');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (44,100,101,'Ulica J. Jesenského', '73');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (45,108,101,'Ulica L. Podjavorinskej', '242');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (46,1,101,'Ulica M. Hodžu', '305');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (47,135,101,'Ulica M. Mišíka', '219');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (48,89,101,'Ulica Matice slovenskej', '224');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (49,74,101,'Ulica na nádvorí', '220');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (50,43,101,'Ulica Š. Moyzesa', '249');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (51,111,101,'Ulica T. Vansovej', '27');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (52,63,101,'Vajanského ulica', '24');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (53,130,101,'Vápenická ulica', '199');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (54,61,101,'Velkolehotská cesta', '65');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (55,80,101,'Vinohradnícka ulica', '167');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (56,3,101,'Vrchy', '50');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (57,78,101,'Východná ulica', '173');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (58,133,101,'Záhradnícka ulica', '41');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (59,28,101,'Zdravotnícka ulica', '72');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (60,96,101,'Ulica M. Hodžu', '130');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (61,21,101,'Ulica M. Mišíka', '252');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (62,134,101,'Ulica Matice slovenskej', '206');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (63,13,101,'Ulica na nádvorí', '157');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (64,82,101,'Ulica Š. Moyzesa', '167');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (65,123,101,'Ulica T. Vansovej', '152');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (66,89,101,'Vajanského ulica', '301');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (67,69,101,'Vápenická ulica', '109');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (68,67,101,'Velkolehotská cesta', '47');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (69,127,101,'Ciglianska cesta', '79');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (70,117,101,'Dlhá ulica', '7');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (71,93,101,'Garážová ulica', '76');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (72,27,101,'Hasicská ulica', '277');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (73,33,101,'Hviezdoslavova ulica', '145');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (74,86,101,'Inžinierska ulica', '308');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (75,85,101,'Kláštorná ulica', '165');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (76,107,101,'Košovská cesta', '210');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (77,1,101,'Kukucínova ulica', '133');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (78,100,101,'Lehotská cesta', '231');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (79,69,101,'Malolehotská ulica', '216');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (80,125,101,'Mariánska ulica', '93');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (81,130,101,'Montážna ulica', '11');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (82,127,101,'Moštenická ulica', '85');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (83,67,101,'Nábrežie A. Kmeta', '300');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (84,119,101,'Nábrežie J. Kalinciaka', '33');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (85,7,101,'Nábrežie sv. Cyrila', '235');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (86,85,101,'Hlboká ulica', '258');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (87,79,101,'Hradecká ulica', '6');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (88,71,101,'Južná ulica', '260');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (89,74,101,'K potoku', '154');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (90,112,101,'Krížna ulica', '110');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (91,79,101,'Lesná ulica', '85');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (92,72,101,'Mlynárska ulica', '179');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (93,30,101,'Mraznicná ulica', '88');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (94,85,101,'Na lánoch', '260');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (95,50,101,'Na lúcky', '77');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (96,4,101,'Na stanište', '167');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (97,57,101,'Na vršku', '275');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (98,73,101,'Na záhrade', '223');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (99,84,101,'Parková ulica', '37');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (100,42,101,'Pavlovská ulica', '139');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (101,56,101,'Pekná ulica', '28');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (102,56,101,'Pod hájik', '243');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (103,132,101,'Pod hôrku', '181');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (104,39,101,'Pod hrádkom', '142');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (105,42,101,'Pod poliankou', '69');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (106,76,101,'Podhorská ulica', '196');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (107,14,101,'Remeselnícka ulica', '17');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (108,10,101,'Richtárska ulica', '173');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (109,85,101,'Rolnícka ulica', '249');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (110,19,101,'Ružová ulica', '190');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (111,62,101,'Spojovacia ulica', '247');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (112,15,101,'Strmá ulica', '293');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (113,126,101,'Súhradská ulica', '114');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (114,53,101,'Školská ulica', '39');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (115,135,101,'Uhlištná ulica', '83');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (116,129,101,'Ulica 1. mája', '108');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (117,34,101,'Ulica družby', '26');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (118,28,101,'Ulica F. Hecku', '14');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (119,101,101,'Ulica J. L. Bellu', '50');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (120,124,101,'Vinicná ulica', '128');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (121,9,101,'Vrchárska ulica', '196');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (122,132,101,'Hlboká ulica', '153');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (123,94,101,'Hradecká ulica', '212');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (124,97,101,'Južná ulica', '237');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (125,41,101,'K potoku', '239');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (126,57,101,'Krížna ulica', '241');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (127,130,101,'Lesná ulica', '89');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (128,77,101,'Mlynárska ulica', '48');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (129,39,101,'Mraznicná ulica', '11');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (130,108,101,'Na lánoch', '126');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (131,12,101,'Na lúcky', '183');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (132,11,101,'Na stanište', '139');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (133,97,101,'Na vršku', '290');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (134,53,101,'Na záhrade', '63');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (135,127,101,'Parková ulica', '99');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (136,115,101,'Pavlovská ulica', '248');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (137,74,101,'Pekná ulica', '127');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (138,55,101,'Pod hájik', '255');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (139,117,101,'Pod hôrku', '86');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (140,47,101,'Pod hrádkom', '176');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (141,94,101,'Pod poliankou', '27');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (142,64,101,'Podhorská ulica', '17');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (143,45,101,'Remeselnícka ulica', '299');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (144,33,101,'Richtárska ulica', '243');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (145,48,101,'Rolnícka ulica', '160');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (146,103,101,'Ružová ulica', '169');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (147,92,101,'Spojovacia ulica', '18');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (148,120,101,'Strmá ulica', '214');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (149,101,101,'Súhradská ulica', '109');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (150,48,101,'Školská ulica', '296');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (151,29,101,'Uhlištná ulica', '194');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (152,120,101,'Ulica 1. mája', '149');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (153,122,101,'Ulica družby', '127');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (154,13,101,'Ulica F. Hecku', '43');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (155,117,101,'Ulica J. L. Bellu', '73');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (156,79,101,'Vinicná ulica', '145');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (157,120,101,'Vrchárska ulica', '283');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (158,4,101,'Strmá ulica', '244');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (159,9,101,'Súhradská ulica', '212');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (160,120,101,'Školská ulica', '120');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (161,24,101,'Uhlištná ulica', '137');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (162,3,101,'Ulica 1. mája', '8');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (163,106,101,'Ulica družby', '134');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (164,86,101,'Ulica F. Hecku', '105');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (165,112,101,'Na lánoch', '54');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (166,87,101,'Na lúcky', '83');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (167,88,101,'Na stanište', '101');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (168,84,101,'Na vršku', '200');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (169,72,101,'Na záhrade', '186');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (170,31,101,'Parková ulica', '304');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (171,48,101,'Rolnícka ulica', '174');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (172,67,101,'Ružová ulica', '90');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (173,66,101,'Agátová ulica', '80');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (174,14,101,'Bazová ulica', '202');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (175,61,101,'Bôrová ulica', '183');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (176,88,101,'Bottova ulica', '133');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (177,90,101,'Buková ulica', '178');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (178,122,101,'Cesta Vl. Clementisa', '142');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (179,85,101,'Dubová ulica', '93');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (180,28,101,'Hrabová ulica', '246');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (181,130,101,'Jánošíkova ulica', '70');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (182,75,101,'Jasenová ulica', '170');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (183,21,101,'Jedlová ulica', '200');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (184,85,101,'Kocelova ulica', '75');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (185,101,101,'Koncová ulica', '47');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (186,71,101,'Lesný park', '116');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (187,42,101,'Lipová ulica', '154');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (188,21,101,'Makovického ulica', '277');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (189,4,101,'Mojmírova ulica', '116');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (190,30,101,'Na karasiny', '122');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (191,129,101,'Nad terasami', '35');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (192,135,101,'Partizánska ulica', '248');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (193,31,101,'Povstalecká ulica', '163');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (194,55,101,'Skrytá ulica', '274');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (195,116,101,'Smreková ulica', '119');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (196,3,101,'Ulica A. Bernoláka', '297');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (197,119,101,'Ulica C. Majerníka', '61');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (198,24,101,'Ulica energetikov', '154');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (199,42,101,'Ulica I. Vysocana', '48');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (200,104,101,'Ulica J. Alexyho', '99');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (201,125,101,'Ulica J. Gramantíka', '57');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (202,91,101,'Ulica J. Záborského', '44');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (203,109,101,'Ulica K. Kuzmányho', '93');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (204,121,101,'Ulica K. Novackého', '286');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (205,105,101,'Ulica M. Benku', '106');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (206,109,101,'Ulica M. Gorkého', '195');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (207,33,101,'Ulica M. Medveckej', '284');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (208,1,101,'Ulica odbojárov', '238');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (209,115,101,'Ulica S. Meciara', '208');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (210,96,101,'Ulica V. Benedikta', '51');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (211,120,101,'Veterná ulica', '209');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (212,95,101,'Átriová ulica', '36');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (213,64,101,'Banícka ulica', '191');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (214,50,101,'Bojnická cesta', '183');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (215,103,101,'Duklianska ulica', '236');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (216,2,101,'Garbiarska ulica', '127');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (217,3,101,'Golfová ulica', '230');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (218,104,101,'Gorazdovo nábrežie', '13');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (219,104,101,'Klampiarska ulica', '68');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (220,3,101,'Krajná ulica', '227');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (221,47,101,'Letisková ulica', '141');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (222,112,101,'Májová ulica', '168');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (223,32,101,'Malá ulica', '241');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (224,121,101,'Malookružná ulica', '123');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (225,86,101,'Max Brose', '225');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (226,45,101,'Mierové námestie', '7');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (227,60,101,'Mlynská ulica', '165');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (228,40,101,'Nábrežná ulica', '251');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (229,29,101,'Námestie J. C. Hronského', '50');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (230,43,101,'Obuvnícka ulica', '38');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (231,116,101,'Okružná cesta', '180');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (232,127,101,'Priama ulica', '25');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (233,29,101,'Priechodná ulica', '224');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (234,135,101,'Rad L. N. Tolstého', '98');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (235,93,101,'Riecna ulica', '105');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (236,4,101,'Sad D. Tatarku', '112');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (237,62,101,'Sadová ulica', '198');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (238,27,101,'Sklenárska ulica', '182');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (239,13,101,'Stredná ulica', '58');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (240,56,101,'Súbežná ulica', '7');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (241,18,101,'Súkennícka ulica', '89');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (242,43,101,'Svätoplukova ulica', '212');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (243,63,101,'Tenisová ulica', '251');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (244,49,101,'Tichá ulica', '216');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (245,55,101,'Tkácska ulica', '75');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (246,36,101,'Trhová ulica', '133');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (247,22,101,'Ulica A. Bednára', '128');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (248,12,101,'Ulica A. H. Gavlovica', '31');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (249,9,101,'Ulica A. Mišúta', '312');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (250,88,101,'Ulica A. Rudnaya', '250');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (251,99,101,'Ulica A. Sládkovica', '147');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (252,89,101,'Ulica A. Stodolu', '305');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (253,57,101,'Ulica B. Björnsona', '294');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (254,43,101,'Ulica D. Krmana', '37');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (255,93,101,'Ulica D. Kubíka', '169');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (256,67,101,'Ulica E. M. Šoltésovej', '204');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (257,25,101,'Ulica F. Madvu', '223');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (258,12,101,'Ulica I. Krasku', '168');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (259,41,101,'Ulica J. Bendíka', '149');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (260,127,101,'Ulica J. Cervena', '300');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (261,24,101,'Ulica J. Fándlyho', '224');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (262,94,101,'Ulica J. Francisciho', '175');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (263,62,101,'Ulica J. G. Tajovského', '227');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (264,58,101,'Ulica J. Kollára', '275');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (265,103,101,'Ulica J. Krála', '171');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (266,79,101,'Ulica J. Matúšku', '291');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (267,46,101,'Ulica J. Murgaša', '281');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (268,41,101,'Ulica J. Okála', '20');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (269,52,101,'Ulica J. Palkovica', '136');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (270,76,101,'Ulica J. Pauleho', '6');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (271,43,101,'Ulica J. Siváka', '180');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (272,57,101,'Ulica J. Škopca', '147');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (273,17,101,'Ulica J. Žirku', '41');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (274,112,101,'Ulica L. Ondrejova', '182');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (275,73,101,'Ulica L. Štúra', '123');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (276,128,101,'Ulica M. Falešníka', '249');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (277,93,101,'Ulica M. R. Štefánika', '9');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (278,135,101,'Ulica olympionikov', '199');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (279,3,101,'Ulica P. Benického', '154');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (280,37,101,'Ulica P. Dobšinského', '173');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (281,115,101,'Ulica R. Jašíka', '15');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (282,110,101,'Ulica S. Chalupku', '290');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (283,107,101,'Ulica Š. Banica', '154');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (284,87,101,'Ulica Š. Králika', '230');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (285,100,101,'Ulica Š. Závodníka', '287');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (286,8,101,'Ulica T. Milkina', '14');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (287,130,101,'Ulica za depom', '2');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (288,71,101,'Úzka ulica', '294');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (289,37,101,'Vnútorná ulica', '218');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (290,73,101,'Zadná ulica', '144');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (291,15,101,'Západná ulica', '121');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (292,75,101,'Ulica Š. Moyzesa', '273');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (293,48,101,'Ulica T. Vansovej', '70');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (294,8,101,'Vajanského ulica', '260');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (295,21,101,'Vápenická ulica', '81');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (296,10,101,'Velkolehotská cesta', '163');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (297,97,101,'Vinohradnícka ulica', '74');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (298,91,101,'Vrchy', '291');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (299,134,101,'Východná ulica', '93');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (300,97,101,'Záhradnícka ulica', '222');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (301,1,101,'Zdravotnícka ulica', '107');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (302,71,101,'Ulica M. Hodžu', '157');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (303,119,101,'Ulica M. Mišíka', '275');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (304,45,101,'Ulica Matice slovenskej', '241');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (305,32,101,'Ulica na nádvorí', '39');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (306,56,101,'Ulica Š. Moyzesa', '50');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (307,33,101,'Ulica T. Vansovej', '98');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (308,122,101,'Vajanského ulica', '69');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (309,50,101,'Vápenická ulica', '301');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (310,84,101,'Velkolehotská cesta', '47');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (311,117,101,'Ciglianska cesta', '200');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (312,52,101,'Dlhá ulica', '71');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (313,68,101,'Garážová ulica', '209');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (314,4,101,'Hasicská ulica', '49');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (315,85,101,'Hviezdoslavova ulica', '248');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (316,32,101,'Inžinierska ulica', '203');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (317,41,101,'Kláštorná ulica', '205');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (318,126,101,'Košovská cesta', '213');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (319,55,101,'Kukucínova ulica', '278');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (320,47,101,'Lehotská cesta', '227');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (321,96,101,'Malolehotská ulica', '100');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (322,131,101,'Mariánska ulica', '134');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (323,101,101,'Montážna ulica', '31');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (324,25,101,'Moštenická ulica', '103');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (325,30,101,'Nábrežie A. Kmeta', '170');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (326,112,101,'Nábrežie J. Kalinciaka', '294');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (327,43,101,'Nábrežie sv. Cyrila', '217');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (328,50,101,'Hlboká ulica', '251');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (329,106,101,'Hradecká ulica', '219');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (330,67,101,'Južná ulica', '269');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (331,60,101,'K potoku', '286');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (332,115,101,'Krížna ulica', '205');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (333,47,101,'Lesná ulica', '5');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (334,133,101,'Mlynárska ulica', '234');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (335,71,101,'Mraznicná ulica', '92');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (336,63,101,'Na lánoch', '18');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (337,55,101,'Na lúcky', '307');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (338,117,101,'Na stanište', '300');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (339,110,101,'Na vršku', '138');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (340,137,101,'Na záhrade', '121');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (341,120,101,'Parková ulica', '267');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (342,4,101,'Pavlovská ulica', '208');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (343,39,101,'Pekná ulica', '312');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (344,115,101,'Pod hájik', '293');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (345,9,101,'Pod hôrku', '3');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (346,128,101,'Pod hrádkom', '3');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (347,63,101,'Pod poliankou', '211');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (348,36,101,'Podhorská ulica', '246');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (349,135,101,'Remeselnícka ulica', '53');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (350,42,101,'Richtárska ulica', '60');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (351,16,101,'Rolnícka ulica', '2');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (352,113,101,'Ružová ulica', '291');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (353,88,101,'Spojovacia ulica', '45');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (354,107,101,'Strmá ulica', '283');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (355,9,101,'Súhradská ulica', '311');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (356,60,101,'Školská ulica', '213');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (357,108,101,'Uhlištná ulica', '301');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (358,97,101,'Ulica 1. mája', '84');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (359,78,101,'Ulica družby', '136');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (360,78,101,'Ulica F. Hecku', '142');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (361,32,101,'Ulica J. L. Bellu', '190');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (362,122,101,'Vinicná ulica', '43');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (363,11,101,'Vrchárska ulica', '309');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (364,84,101,'Hlboká ulica', '304');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (365,16,101,'Hradecká ulica', '91');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (366,124,101,'Južná ulica', '78');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (367,57,101,'K potoku', '34');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (368,30,101,'Krížna ulica', '60');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (369,70,101,'Lesná ulica', '228');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (370,107,101,'Mlynárska ulica', '115');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (371,93,101,'Mraznicná ulica', '277');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (372,103,101,'Na lánoch', '10');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (373,99,101,'Na lúcky', '279');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (374,68,101,'Na stanište', '286');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (375,85,101,'Na vršku', '140');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (376,127,101,'Na záhrade', '214');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (377,137,101,'Parková ulica', '114');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (378,132,101,'Pavlovská ulica', '194');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (379,35,101,'Pekná ulica', '225');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (380,39,101,'Pod hájik', '12');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (381,127,101,'Pod hôrku', '27');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (382,82,101,'Pod hrádkom', '292');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (383,91,101,'Pod poliankou', '5');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (384,54,101,'Podhorská ulica', '138');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (385,3,101,'Remeselnícka ulica', '200');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (386,117,101,'Richtárska ulica', '11');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (387,137,101,'Rolnícka ulica', '132');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (388,16,101,'Ružová ulica', '293');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (389,113,101,'Spojovacia ulica', '246');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (390,38,101,'Strmá ulica', '177');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (391,38,101,'Súhradská ulica', '201');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (392,120,101,'Školská ulica', '29');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (393,88,101,'Uhlištná ulica', '147');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (394,115,101,'Ulica 1. mája', '269');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (395,86,101,'Ulica družby', '99');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (396,20,101,'Ulica F. Hecku', '48');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (397,106,101,'Ulica J. L. Bellu', '20');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (398,109,101,'Vinicná ulica', '121');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (399,44,101,'Vrchárska ulica', '172');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (400,24,101,'Strmá ulica', '28');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (401,55,101,'Súhradská ulica', '242');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (402,6,101,'Školská ulica', '66');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (403,34,101,'Uhlištná ulica', '167');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (404,10,101,'Ulica 1. mája', '108');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (405,120,101,'Ulica družby', '92');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (406,111,101,'Ulica F. Hecku', '219');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (407,64,101,'Na lánoch', '168');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (408,16,101,'Na lúcky', '216');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (409,99,101,'Na stanište', '87');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (410,25,101,'Na vršku', '7');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (411,104,101,'Na záhrade', '33');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (412,7,101,'Parková ulica', '277');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (413,53,101,'Rolnícka ulica', '165');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (414,126,101,'Ružová ulica', '302');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (415,80,101,'Agátová ulica', '55');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (416,119,101,'Bazová ulica', '238');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (417,112,101,'Bôrová ulica', '255');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (418,8,101,'Bottova ulica', '49');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (419,76,101,'Buková ulica', '215');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (420,76,101,'Cesta Vl. Clementisa', '8');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (421,77,101,'Bakalárska ulica', '186');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (422,133,101,'Cesta pod Banskou', '7');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (423,126,101,'Cesta pod skalou', '134');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (424,116,101,'Cesta polnohospodárov', '238');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (425,53,101,'Ciglianska cesta', '106');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (426,97,101,'Dlhá ulica', '106');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (427,88,101,'Garážová ulica', '38');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (428,63,101,'Hasicská ulica', '165');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (429,83,101,'Hviezdoslavova ulica', '102');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (430,92,101,'Inžinierska ulica', '169');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (431,95,101,'Kláštorná ulica', '120');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (432,133,101,'Košovská cesta', '115');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (433,65,101,'Kukucínova ulica', '6');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (434,41,101,'Lehotská cesta', '95');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (435,109,101,'Malolehotská ulica', '253');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (436,132,101,'Mariánska ulica', '32');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (437,46,101,'Montážna ulica', '249');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (438,88,101,'Moštenická ulica', '240');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (439,8,101,'Nábrežie A. Kmeta', '52');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (440,113,101,'Nábrežie J. Kalinciaka', '81');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (441,135,101,'Nábrežie sv. Cyrila', '30');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (442,4,101,'Nábrežie sv. Metoda', '136');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (443,98,101,'Nadjazdová ulica', '141');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (444,53,101,'Námestie slobody', '252');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (445,96,101,'Necpalská cesta', '111');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (446,76,101,'Nová ulica', '115');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (447,86,101,'Osadová cesta', '220');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (448,116,101,'Podjazdová ulica', '254');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (449,81,101,'Pribinovo námestie', '210');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (450,81,101,'Priemyselná ulica', '71');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (451,44,101,'Púšt', '239');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (452,54,101,'Rastislavova ulica', '297');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (453,138,101,'Sebedražská cesta', '9');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (454,23,101,'Severná ulica', '1');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (455,78,101,'Sitnianskeho ulica', '209');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (456,34,101,'Skladová ulica', '10');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (457,21,101,'Strojárska ulica', '227');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (458,14,101,'Šumperská ulica', '63');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (459,104,101,'Teplárenská ulica', '194');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (460,119,101,'Ulica A. Hlinku', '77');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (461,136,101,'Ulica A. Škarvana', '35');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (462,30,101,'Ulica G. Švéniho', '259');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (463,19,101,'Ulica J. Hollého', '159');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (464,42,101,'Ulica J. Jesenského', '138');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (465,71,101,'Ulica L. Podjavorinskej', '150');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (466,100,101,'Ulica M. Hodžu', '262');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (467,39,101,'Ulica M. Mišíka', '44');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (468,45,101,'Ulica Matice slovenskej', '203');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (469,5,101,'Ulica na nádvorí', '254');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (470,138,101,'Ulica Š. Moyzesa', '32');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (471,121,101,'Ulica T. Vansovej', '243');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (472,46,101,'Vajanského ulica', '252');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (473,73,101,'Vápenická ulica', '133');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (474,108,101,'Velkolehotská cesta', '71');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (475,5,101,'Vinohradnícka ulica', '308');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (476,55,101,'Vrchy', '6');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (477,7,101,'Východná ulica', '205');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (478,129,101,'Záhradnícka ulica', '288');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (479,74,101,'Zdravotnícka ulica', '233');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (480,74,101,'Ulica M. Hodžu', '129');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (481,3,101,'Ulica M. Mišíka', '127');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (482,66,101,'Ulica Matice slovenskej', '46');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (483,99,101,'Ulica na nádvorí', '239');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (484,52,101,'Ulica Š. Moyzesa', '293');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (485,128,101,'Ulica T. Vansovej', '29');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (486,93,101,'Vajanského ulica', '36');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (487,87,101,'Vápenická ulica', '31');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (488,74,101,'Velkolehotská cesta', '140');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (489,56,101,'Ciglianska cesta', '274');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (490,4,101,'Dlhá ulica', '128');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (491,75,101,'Garážová ulica', '179');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (492,51,101,'Hasicská ulica', '78');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (493,104,101,'Hviezdoslavova ulica', '148');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (494,12,101,'Inžinierska ulica', '35');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (495,116,101,'Kláštorná ulica', '212');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (496,6,101,'Košovská cesta', '192');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (497,81,101,'Kukucínova ulica', '138');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (498,113,101,'Lehotská cesta', '201');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (499,42,101,'Malolehotská ulica', '27');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (500,12,101,'Mariánska ulica', '175');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (501,4,101,'Montážna ulica', '84');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (502,129,101,'Moštenická ulica', '276');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (503,124,101,'Nábrežie A. Kmeta', '99');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (504,32,101,'Nábrežie J. Kalinciaka', '251');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (505,70,101,'Nábrežie sv. Cyrila', '16');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (506,5,101,'Hlboká ulica', '208');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (507,64,101,'Hradecká ulica', '274');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (508,66,101,'Južná ulica', '40');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (509,58,101,'K potoku', '14');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (510,35,101,'Krížna ulica', '308');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (511,110,101,'Lesná ulica', '254');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (512,27,101,'Mlynárska ulica', '217');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (513,132,101,'Mraznicná ulica', '115');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (514,24,101,'Na lánoch', '51');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (515,28,101,'Na lúcky', '204');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (516,81,101,'Na stanište', '26');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (517,61,101,'Na vršku', '109');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (518,117,101,'Na záhrade', '55');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (519,43,101,'Parková ulica', '301');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (520,100,101,'Pavlovská ulica', '313');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (521,92,101,'Pekná ulica', '257');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (522,75,101,'Pod hájik', '23');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (523,52,101,'Pod hôrku', '164');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (524,89,101,'Pod hrádkom', '243');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (525,6,101,'Pod poliankou', '184');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (526,37,101,'Podhorská ulica', '199');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (527,106,101,'Remeselnícka ulica', '40');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (528,52,101,'Richtárska ulica', '260');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (529,36,101,'Rolnícka ulica', '231');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (530,106,101,'Ružová ulica', '147');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (531,96,101,'Spojovacia ulica', '308');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (532,44,101,'Strmá ulica', '139');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (533,70,101,'Súhradská ulica', '85');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (534,1,101,'Školská ulica', '167');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (535,129,101,'Uhlištná ulica', '241');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (536,47,101,'Ulica 1. mája', '158');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (537,104,101,'Ulica družby', '246');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (538,39,101,'Ulica F. Hecku', '272');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (539,65,101,'Ulica J. L. Bellu', '192');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (540,116,101,'Vinicná ulica', '249');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (541,104,101,'Vrchárska ulica', '250');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (542,45,101,'Hlboká ulica', '109');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (543,88,101,'Hradecká ulica', '61');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (544,15,101,'Južná ulica', '296');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (545,11,101,'K potoku', '106');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (546,68,101,'Krížna ulica', '195');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (547,61,101,'Lesná ulica', '98');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (548,27,101,'Mlynárska ulica', '123');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (549,122,101,'Mraznicná ulica', '22');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (550,43,101,'Na lánoch', '14');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (551,99,101,'Na lúcky', '15');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (552,47,101,'Na stanište', '186');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (553,27,101,'Na vršku', '251');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (554,13,101,'Na záhrade', '60');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (555,116,101,'Parková ulica', '16');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (556,113,101,'Pavlovská ulica', '104');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (557,64,101,'Pekná ulica', '146');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (558,89,101,'Pod hájik', '159');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (559,84,101,'Pod hôrku', '255');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (560,98,101,'Pod hrádkom', '175');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (561,80,101,'Ulica stavbárov', '295');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (562,129,101,'Urbánkova ulica', '102');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (563,5,101,'Urbárska ulica', '217');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (564,9,101,'Vcelárska ulica', '17');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (565,26,101,'Velkonecpalská ulica', '303');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (566,23,101,'Zelená ulica', '132');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (567,112,101,'Železniciarska ulica', '220');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (568,74,101,'Astrová ulica', '230');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (569,39,101,'Dúbravská ulica', '217');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (570,12,101,'Fialková ulica', '51');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (571,90,101,'Gazdovská ulica', '65');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (572,7,101,'Hornonitrianska cesta', '272');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (573,38,101,'Hrnciarska ulica', '90');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (574,76,101,'Jégého ulica', '162');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (575,91,101,'Klinceková ulica', '153');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (576,85,101,'Konvalinková ulica', '209');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (577,114,101,'Krátka ulica', '31');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (578,23,101,'Kútovská ulica', '234');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (579,54,101,'Kvetná ulica', '47');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (580,18,101,'Lúcna ulica', '6');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (581,64,101,'Majerská ulica', '136');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (582,56,101,'Malonecpalská ulica', '67');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (583,87,101,'Medzibriežková ulica', '291');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (584,98,101,'Mliekarenská ulica', '246');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (585,68,101,'Na stránach', '236');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (586,124,101,'Na záhumní', '27');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (587,78,101,'Narcisová ulica', '229');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (588,101,101,'Necpalská cesta', '259');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (589,94,101,'Nedožerská cesta', '295');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (590,56,101,'Nezábudková ulica', '34');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (591,115,101,'Pod horou', '133');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (592,36,101,'Polná ulica', '233');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (593,29,101,'Prírodná ulica', '139');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (594,107,101,'Puškinova ulica', '169');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (595,7,101,'Slnecná ulica', '117');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (596,64,101,'Agátová ulica', '8');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (597,37,101,'Bazová ulica', '215');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (598,100,101,'Bôrová ulica', '105');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (599,138,101,'Bottova ulica', '235');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (600,43,101,'Buková ulica', '194');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (601,40,101,'Cesta Vl. Clementisa', '247');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (602,115,101,'Dubová ulica', '46');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (603,45,101,'Hrabová ulica', '229');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (604,8,101,'Jánošíkova ulica', '101');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (605,104,101,'Jasenová ulica', '162');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (606,134,101,'Jedlová ulica', '176');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (607,39,101,'Kocelova ulica', '34');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (608,40,101,'Koncová ulica', '187');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (609,63,101,'Lesný park', '215');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (610,89,101,'Lipová ulica', '150');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (611,75,101,'Makovického ulica', '85');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (612,88,101,'Mojmírova ulica', '236');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (613,36,101,'Na karasiny', '8');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (614,116,101,'Nad terasami', '51');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (615,66,101,'Partizánska ulica', '39');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (616,104,101,'Povstalecká ulica', '78');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (617,98,101,'Rakytová ulica', '195');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (618,108,101,'Rovná ulica', '108');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (619,66,101,'Skrytá ulica', '84');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (620,98,101,'Smreková ulica', '168');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (621,28,101,'Ulica A. Bernoláka', '135');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (622,115,101,'Ulica C. Majerníka', '107');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (623,30,101,'Ulica energetikov', '115');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (624,70,101,'Ulica I. Vysocana', '215');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (625,22,101,'Ulica J. Alexyho', '290');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (626,138,101,'Ulica J. Gramantíka', '235');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (627,12,101,'Ulica J. Záborského', '171');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (628,100,101,'Ulica K. Kuzmányho', '109');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (629,57,101,'Ulica K. Novackého', '54');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (630,38,101,'Ulica M. Benku', '269');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (631,73,101,'Ulica M. Gorkého', '224');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (632,120,101,'Ulica M. Medveckej', '234');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (633,8,101,'Ulica odbojárov', '3');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (634,19,101,'Ulica S. Meciara', '60');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (635,1,101,'Ulica V. Benedikta', '271');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (636,78,101,'Veterná ulica', '225');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (637,17,101,'Átriová ulica', '80');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (638,137,101,'Banícka ulica', '305');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (639,135,101,'Bojnická cesta', '187');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (640,116,101,'Duklianska ulica', '2');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (641,5,101,'Garbiarska ulica', '168');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (642,119,101,'Golfová ulica', '117');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (643,110,101,'Gorazdovo nábrežie', '121');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (644,57,101,'Klampiarska ulica', '146');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (645,12,101,'Krajná ulica', '248');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (646,129,101,'Letisková ulica', '134');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (647,106,101,'Májová ulica', '258');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (648,66,101,'Malá ulica', '50');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (649,123,101,'Malookružná ulica', '130');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (650,133,101,'Max Brose', '106');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (651,5,101,'Mierové námestie', '28');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (652,18,101,'Mlynská ulica', '222');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (653,46,101,'Nábrežná ulica', '121');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (654,10,101,'Námestie J. C. Hronského', '197');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (655,34,101,'Obuvnícka ulica', '167');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (656,66,101,'Okružná cesta', '298');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (657,70,101,'Priama ulica', '249');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (658,62,101,'Priechodná ulica', '240');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (659,117,101,'Rad L. N. Tolstého', '130');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (660,97,101,'Riecna ulica', '275');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (661,124,101,'Sad D. Tatarku', '299');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (662,68,101,'Sadová ulica', '177');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (663,4,101,'Sklenárska ulica', '184');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (664,65,101,'Stredná ulica', '4');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (665,27,101,'Súbežná ulica', '62');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (666,95,101,'Súkennícka ulica', '249');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (667,92,101,'Svätoplukova ulica', '302');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (668,40,101,'Tenisová ulica', '257');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (669,101,101,'Tichá ulica', '187');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (670,77,101,'Tkácska ulica', '42');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (671,95,101,'Trhová ulica', '70');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (672,105,101,'Ulica A. Bednára', '211');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (673,90,101,'Ulica A. H. Gavlovica', '163');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (674,52,101,'Ulica A. Mišúta', '265');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (675,54,101,'Ulica A. Rudnaya', '54');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (676,119,101,'Ulica A. Sládkovica', '69');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (677,129,101,'Ulica A. Stodolu', '253');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (678,112,101,'Ulica B. Björnsona', '217');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (679,95,101,'Ulica D. Krmana', '207');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (680,119,101,'Ulica D. Kubíka', '57');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (681,98,101,'Ulica E. M. Šoltésovej', '44');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (682,38,101,'Ulica F. Madvu', '131');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (683,94,101,'Ulica I. Krasku', '313');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (684,91,101,'Ulica J. Bendíka', '202');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (685,11,101,'Ulica J. Cervena', '25');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (686,97,101,'Ulica J. Fándlyho', '140');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (687,84,101,'Ulica J. Francisciho', '172');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (688,12,101,'Ulica J. G. Tajovského', '48');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (689,135,101,'Ulica J. Kollára', '166');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (690,95,101,'Ulica J. Krála', '273');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (691,78,101,'Ulica J. Matúšku', '2');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (692,56,101,'Ulica J. Murgaša', '233');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (693,48,101,'Ulica J. Okála', '292');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (694,137,101,'Ulica J. Palkovica', '289');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (695,67,101,'Ulica J. Pauleho', '210');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (696,18,101,'Ulica J. Siváka', '150');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (697,5,101,'Ulica J. Škopca', '28');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (698,70,101,'Ulica J. Žirku', '304');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (699,90,101,'Ulica L. Ondrejova', '92');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (700,37,101,'Ulica L. Štúra', '14');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (701,42,101,'Ulica M. Falešníka', '204');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (702,78,101,'Ulica M. R. Štefánika', '54');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (703,136,101,'Ulica olympionikov', '102');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (704,125,101,'Ulica P. Benického', '13');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (705,17,101,'Ulica P. Dobšinského', '48');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (706,65,101,'Ulica R. Jašíka', '40');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (707,104,101,'Ulica S. Chalupku', '262');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (708,132,101,'Ulica Š. Banica', '6');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (709,59,101,'Ulica Š. Králika', '44');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (710,81,101,'Ulica Š. Závodníka', '41');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (711,59,101,'Ulica T. Milkina', '73');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (712,75,101,'Ulica za depom', '205');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (713,138,101,'Úzka ulica', '297');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (714,60,101,'Vnútorná ulica', '61');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (715,131,101,'Zadná ulica', '103');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (716,34,101,'Západná ulica', '12');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (717,137,101,'Púšt', '275');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (718,64,101,'Rastislavova ulica', '252');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (719,118,101,'Sebedražská cesta', '181');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (720,76,101,'Severná ulica', '50');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (721,84,101,'Sitnianskeho ulica', '126');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (722,124,101,'Skladová ulica', '24');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (723,82,101,'Strojárska ulica', '1');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (724,39,101,'Šumperská ulica', '242');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (725,41,101,'Teplárenská ulica', '124');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (726,54,101,'Ulica A. Hlinku', '31');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (727,15,101,'Ulica A. Škarvana', '228');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (728,53,101,'Ulica G. Švéniho', '49');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (729,95,101,'Ulica J. Hollého', '260');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (730,114,101,'Ulica J. Jesenského', '102');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (731,117,101,'Ulica L. Podjavorinskej', '17');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (732,85,101,'Ulica M. Hodžu', '64');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (733,47,101,'Ulica M. Mišíka', '19');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (734,15,101,'Ulica Matice slovenskej', '13');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (735,18,101,'Ulica na nádvorí', '289');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (736,129,101,'Ulica Š. Moyzesa', '277');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (737,137,101,'Ulica T. Vansovej', '50');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (738,6,101,'Vajanského ulica', '305');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (739,3,101,'Vápenická ulica', '176');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (740,129,101,'Velkolehotská cesta', '166');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (741,135,101,'Vinohradnícka ulica', '204');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (742,20,101,'Vrchy', '278');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (743,89,101,'Východná ulica', '260');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (744,40,101,'Záhradnícka ulica', '65');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (745,57,101,'Zdravotnícka ulica', '312');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (746,7,101,'Nová ulica', '258');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (747,118,101,'Osadová cesta', '145');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (748,105,101,'Podjazdová ulica', '258');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (749,69,101,'Pribinovo námestie', '223');
insert into d_adresa(id_adresy,id_mesta, id_krajiny, ulica, cislo) values (750,122,101,'Priemyselná ulica', '14');
