insert into typ_dane(ID_TYP_DANE, nazov_dane) VALUES('1', 'dan z motorových vozidiel');
insert into typ_dane(ID_TYP_DANE, nazov_dane) VALUES('2', 'dan za alkohol');
insert into typ_dane(ID_TYP_DANE, nazov_dane) VALUES('3', 'dan za benzin');
insert into typ_dane(ID_TYP_DANE, nazov_dane) VALUES('4', 'DPH');
insert into typ_dane(ID_TYP_DANE, nazov_dane) VALUES('5', 'DPH na knihy');
insert into typ_dane(ID_TYP_DANE, nazov_dane) VALUES('6', 'DPH na lieky');
insert into typ_dane(ID_TYP_DANE, nazov_dane) VALUES('7', 'emisna dan');
insert into typ_dane(ID_TYP_DANE, nazov_dane) VALUES('9', 'dan za mliecne vyrobky');
insert into typ_dane(ID_TYP_DANE, nazov_dane) VALUES('10', 'milionarska dan');
insert into typ_dane(ID_TYP_DANE, nazov_dane) VALUES('11', 'dan zo zisku');
insert into typ_dane(ID_TYP_DANE, nazov_dane) VALUES('12', 'dan za biele pecivo');
insert into typ_dane(ID_TYP_DANE, nazov_dane) VALUES('13', 'dan za tabak');
insert into typ_dane(ID_TYP_DANE, nazov_dane) VALUES('14', 'dan za pivo');
insert into typ_dane(ID_TYP_DANE, nazov_dane) VALUES('15', 'dan za vzduch');
insert into typ_dane(ID_TYP_DANE, nazov_dane) VALUES('16', 'dan za domace zviera');
insert into typ_dane(ID_TYP_DANE, nazov_dane) VALUES('17', 'dan za drahe kovy');
insert into typ_dane(ID_TYP_DANE, nazov_dane) VALUES('18', 'dan za odpad');
insert into typ_dane(ID_TYP_DANE, nazov_dane) VALUES('19', 'mestska dan za ubytovanie');
insert into typ_dane(ID_TYP_DANE, nazov_dane) VALUES('20', 'dan za zriadenie terasy');
