INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (1,'Romania');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (2,'Latvia');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (3,'Iceland');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (4,'United States Minor Outlying Islands');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (5,'Argentina');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (6,'Solomon Islands');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (7,'Luxembourg');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (8,'Cameroon');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (9,'Faroe Islands');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (10,'Eritrea');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (11,'Macao');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (12,'Luxembourg');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (13,'Brunei');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (14,'Burundi');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (15,'Angola');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (16,'Gibraltar');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (17,'San Marino');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (18,'Latvia');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (19,'Bonaire, Sint Eustatius and Saba');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (20,'Gibraltar');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (21,'Lebanon');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (22,'Kyrgyzstan');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (23,'Turkey');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (24,'Bosnia and Herzegovina');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (25,'Iceland');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (26,'Panama');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (27,'Venezuela');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (28,'Falkland Islands');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (29,'Cuba');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (30,'Zambia');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (31,'Paraguay');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (32,'Antarctica');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (33,'Guatemala');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (34,'Equatorial Guinea');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (35,'Svalbard and Jan Mayen Islands');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (36,'Tanzania');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (37,'Sudan');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (38,'Norway');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (39,'Bolivia');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (40,'Malawi');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (41,'Serbia');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (42,'Saint Barthélemy');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (43,'French Guiana');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (44,'Reunion');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (45,'Canada');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (46,'Lebanon');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (47,'Tonga');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (48,'Bhutan');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (49,'Afghanistan');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (50,'Anguilla');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (51,'Ireland');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (52,'New Zealand');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (53,'Uruguay');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (54,'Martinique');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (55,'Nicaragua');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (56,'Uzbekistan');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (57,'Turkmenistan');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (58,'Cyprus');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (59,'Mexico');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (60,'Svalbard and Jan Mayen Islands');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (61,'Viet Nam');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (62,'Israel');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (63,'Switzerland');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (64,'New Caledonia');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (65,'Cyprus');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (66,'Gambia');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (67,'Honduras');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (68,'Japan');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (69,'Iceland');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (70,'Lithuania');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (71,'Gibraltar');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (72,'Uzbekistan');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (73,'Saint Barthélemy');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (74,'Liechtenstein');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (75,'Nepal');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (76,'Serbia');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (77,'Czech Republic');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (78,'Montenegro');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (79,'Serbia');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (80,'Vanuatu');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (81,'Cameroon');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (82,'Azerbaijan');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (83,'Morocco');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (84,'Nicaragua');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (85,'France');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (86,'Guinea-Bissau');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (87,'South Sudan');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (88,'United Arab Emirates');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (89,'Bahamas');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (90,'Poland');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (91,'Martinique');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (92,'Panama');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (93,'Finland');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (94,'Equatorial Guinea');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (95,'Kazakhstan');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (96,'Madagascar');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (97,'Chad');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (98,'Saint Pierre and Miquelon');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (99,'Iraq');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (100,'French Guiana');
INSERT INTO d_krajina (id_krajiny,nazov_statu) VALUES (101,'Slovakia');
