INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (1, to_date('01.01.11','DD.MM.RR'), 10);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (2, to_date('01.01.11','DD.MM.RR'), 3);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (3, to_date('01.01.11','DD.MM.RR'), 12);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (4, to_date('01.01.11','DD.MM.RR'), 11);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (5, to_date('01.01.11','DD.MM.RR'), 32);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (6, to_date('01.01.11','DD.MM.RR'), 12);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (7, to_date('01.01.11','DD.MM.RR'), 54);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (8, to_date('01.01.11','DD.MM.RR'), 23);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (9, to_date('01.01.11','DD.MM.RR'), 4);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (10, to_date('01.01.11','DD.MM.RR'), 5);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (11, to_date('01.01.11','DD.MM.RR'), 34);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (12, to_date('01.01.11','DD.MM.RR'), 54);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (13, to_date('01.01.11','DD.MM.RR'), 4);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (14, to_date('01.01.11','DD.MM.RR'), 3);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (15, to_date('01.01.11','DD.MM.RR'), 33);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (16, to_date('01.01.11','DD.MM.RR'), 22);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (17, to_date('01.01.11','DD.MM.RR'), 21);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (18, to_date('01.01.11','DD.MM.RR'), 10);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (19, to_date('01.01.11','DD.MM.RR'), 23);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (20, to_date('01.01.11','DD.MM.RR'), 9);

INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (1, to_date('01.01.12','DD.MM.RR'), 11);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (2, to_date('01.01.12','DD.MM.RR'), 4);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (3, to_date('01.01.12','DD.MM.RR'), 15);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (4, to_date('01.01.12','DD.MM.RR'), 13);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (5, to_date('01.01.12','DD.MM.RR'), 32);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (6, to_date('01.01.12','DD.MM.RR'), 11);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (7, to_date('01.01.12','DD.MM.RR'), 51);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (8, to_date('01.01.12','DD.MM.RR'), 21);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (9, to_date('01.01.12','DD.MM.RR'), 4);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (10, to_date('01.01.12','DD.MM.RR'), 2);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (11, to_date('01.01.12','DD.MM.RR'), 4);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (12, to_date('01.01.12','DD.MM.RR'), 4);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (13, to_date('01.01.12','DD.MM.RR'), 22);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (14, to_date('01.01.12','DD.MM.RR'), 13);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (15, to_date('01.01.12','DD.MM.RR'), 3);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (16, to_date('01.01.12','DD.MM.RR'), 12);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (17, to_date('01.01.12','DD.MM.RR'), 11);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (18, to_date('01.01.12','DD.MM.RR'), 11);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (19, to_date('01.01.12','DD.MM.RR'), 21);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (20, to_date('01.01.12','DD.MM.RR'), 19);

INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (1, to_date('01.01.14','DD.MM.RR'), 10);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (2, to_date('01.01.14','DD.MM.RR'), 4);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (3, to_date('01.01.14','DD.MM.RR'), 10);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (4, to_date('01.01.14','DD.MM.RR'), 10);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (5, to_date('01.01.14','DD.MM.RR'), 30);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (6, to_date('01.01.14','DD.MM.RR'), 10);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (7, to_date('01.01.14','DD.MM.RR'), 48);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (8, to_date('01.01.14','DD.MM.RR'), 20);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (9, to_date('01.01.14','DD.MM.RR'), 4);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (10, to_date('01.01.14','DD.MM.RR'), 12);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (11, to_date('01.01.14','DD.MM.RR'), 14);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (12, to_date('01.01.14','DD.MM.RR'), 14);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (13, to_date('01.01.14','DD.MM.RR'), 20);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (14, to_date('01.01.14','DD.MM.RR'), 10);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (15, to_date('01.01.14','DD.MM.RR'), 6);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (16, to_date('01.01.14','DD.MM.RR'), 10);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (17, to_date('01.01.14','DD.MM.RR'), 10);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (18, to_date('01.01.14','DD.MM.RR'), 10);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (19, to_date('01.01.14','DD.MM.RR'), 20);
INSERT INTO d_dan(id_typ_dane, datum_od, percento) VALUES (20, to_date('01.01.14','DD.MM.RR'), 10);

update d_dan set datum_do=to_date('31.12.11','DD.MM.RR') where datum_od=to_date('01.01.11','DD.MM.RR');
update d_dan set datum_do=to_date('31.12.13','DD.MM.RR') where datum_od=to_date('01.01.12','DD.MM.RR');

